version: "2"
services:
    db:
        image: postgres:9.5
        container_name: postgres
        environment:
            # postgres/mysecretpassword are the default user/password from the
            # official image. Eventually we need to extend the image and create
            # our own init scripts for separate db, user, etc.
            POSTGRES_USER : postgres
            POSTGRES_PASSWORD : mysecretpassword

    owncloud:
        image: rwakida/owncloud:9.0-apache
        container_name: owncloud
        depends_on:
            - db
        ports: 
            - "80:80"
        volumes:
            - /opt/owncloud/apps:/var/www/html/apps
            - /opt/owncloud/config:/var/www/html/config
            - /opt/owncloud/data:/var/www/html/data
        links:
            - "db:postgres"
